### ISSUE TITLE
Doc suggestions

### ISSUE THREAD

**Issue by gaumondp** [Kephson/reint_file_timestamp#1]
Quick suggestions in the "what does it do" section :
1. Show some URLs before & after installing the extension.
2. I presumed it doesn't impact images from templates and visual in general. It could be specified.
3. Was it tested with RealURL ?

**Comment by Kephson** [comment]
Hi thanks for moving this issue to the correct repo.
1. I will add this information to the documentation, this is what you want to know, am I right?
2. The extension also adds a timestamp parameter to images in templates if they aren't converted through image processor. I will add this to documentation, too.
3. We're using RealURL for our sites and there is no problem found at the moment, because RealURL isn't parsing the Public-URL of a file as I know.

If there is a development system where you can test the extension you can try it out: Just install it and disable it, if there are problems. The extension isn't doing any processing of files or changing something with files.
It only modifies the public url of a file, not the file itself.

**Comment by gaumondp** [comment]
It's not out of laziness. I'm just sending suggestions for an extension that could be useful for others and since I got those questions just by reading, I presumed it was worth suggesting those additions.

As for #1 I was just curious of the look of urls before installing the extension. I presumed it would be something like : 

/fileadmin/report.pdf?5456327411 

It just help people deciding if it does what they think it will achieve and solve their "problem" / requirement. You wrote there's no configuration so it's good to know the final output.

Anyway, having already made documentation is a step many people don't even care to do before sending to TER so congrats! :)

**Comment by Kephson** [comment]
Thanks a lot, I'm very happy to get feedback and could update the documentation to help people understand what it does.
Without documentation I will not upload an extension to TER ;-).
I updated the documentation, please give me feedback if its better now.

**Comment by gaumondp** [comment]
Crystal clear.

I would suggest a tiny last adjustment : 

"What doesn't it do?" to simply: "It will not :" and make shorter sentences then :  
Modify the file itself, it only modifies the public URL of the file when the URL is asked for.
Modify the public URL if a file is processed through TYPO3 image processing. A timestamp for such  processed URLs is not needed.

Good work !

**Comment by Kephson** [comment]
Thanks, I pushed some small updates for documentation and released version 1.0.3 in TER.
